name: Actions Workflow 

on: [push] 

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest 
    steps: 
      - name: checkout 
        uses: actions/checkout@v1

      - name: Simpls JS Action
        id: greet  
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: John

      - name: Log Greeting Time 
        run: echo "${{ steps.greet.output.time }}"
        
