name: anatomy 

on: [push] 

jobs:
  run-shell-commands: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      
      - name: multiline script 
        run: |
          node -v 
          npm -v 

      - name: python command 
        run: |
          import platform 
          print(platform.processor())
        shell: python 

      - name: Using custom environment variables 
        run: node -v
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432 
      
      - name: install softwares 
        run: npm install -g bats
  
      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash

  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-commands"]
    steps:
      - name: Directory Powershell 
        run: Get-Location
      
      - name: Directory Bash 
        run: pwd 
        shell: bash 